//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpPDDL.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpPDDL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Some problem in adding goal..
        /// </summary>
        internal static string C0 {
            get {
                return ResourceManager.GetString("C0", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Its impossible to find {0} param inside {1} node..
        /// </summary>
        internal static string C1 {
            get {
                return ResourceManager.GetString("C1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu internal error in EffectLambdaPDDL constructor: allTypes collection is null.
        /// </summary>
        internal static string C10 {
            get {
                return ResourceManager.GetString("C10", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu internal error in EffectLambdaPDDL constructor: allTypes collection is empty.
        /// </summary>
        internal static string C11 {
            get {
                return ResourceManager.GetString("C11", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu internal error in EffectLambdaPDDL constructor: paramsIndexesInAction collection is null.
        /// </summary>
        internal static string C12 {
            get {
                return ResourceManager.GetString("C12", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu internal error in EffectLambdaPDDL constructor: paramsIndexesInAction collection is empty.
        /// </summary>
        internal static string C13 {
            get {
                return ResourceManager.GetString("C13", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected error in time of Effect&apos;s function changing: {0}.
        /// </summary>
        internal static string C14 {
            get {
                return ResourceManager.GetString("C14", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wrong / Unknown type: {0} inside Effect funct.
        /// </summary>
        internal static string C15 {
            get {
                return ResourceManager.GetString("C15", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You cannot to use object method call to create model of object. Try to write this method ({0}) as new lambda which uses only ValueType member(s) of object..
        /// </summary>
        internal static string C16 {
            get {
                return ResourceManager.GetString("C16", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Effects 1-arg; There is no {0} param at list. {1}.
        /// </summary>
        internal static string C17 {
            get {
                return ResourceManager.GetString("C17", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Effects 2-arg; There is no 1st {0} param at list. {1}.
        /// </summary>
        internal static string C18 {
            get {
                return ResourceManager.GetString("C18", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Effects 2-arg; There is no 2nd {0} param at list. {1}.
        /// </summary>
        internal static string C19 {
            get {
                return ResourceManager.GetString("C19", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu uncaught bug of wrong (empty, or null) name.
        /// </summary>
        internal static string C2 {
            get {
                return ResourceManager.GetString("C2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expression Execution 1-arg; There is no {0} param at list. {1}.
        /// </summary>
        internal static string C20 {
            get {
                return ResourceManager.GetString("C20", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expression Execution 2-arg; There is no 1st {0} param at list. {1}.
        /// </summary>
        internal static string C21 {
            get {
                return ResourceManager.GetString("C21", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expression Execution 2-arg; There is no 2nd {0} param at list. {1}.
        /// </summary>
        internal static string C22 {
            get {
                return ResourceManager.GetString("C22", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected error in time of {0} action execution function building.
        /// </summary>
        internal static string C23 {
            get {
                return ResourceManager.GetString("C23", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu allTypes cannot be the null while goal lambda building.
        /// </summary>
        internal static string C24 {
            get {
                return ResourceManager.GetString("C24", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu allTypes cannot be empty collection while goal lambda building.
        /// </summary>
        internal static string C25 {
            get {
                return ResourceManager.GetString("C25", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OryginalObjectType cannot be null while goal lambda building.
        /// </summary>
        internal static string C26 {
            get {
                return ResourceManager.GetString("C26", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected error in time of goal function building.
        /// </summary>
        internal static string C27 {
            get {
                return ResourceManager.GetString("C27", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wrong / Unknown type: {0} inside Goal funct.
        /// </summary>
        internal static string C28 {
            get {
                return ResourceManager.GetString("C28", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected error in time of goal function changing {0}.
        /// </summary>
        internal static string C29 {
            get {
                return ResourceManager.GetString("C29", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wrong object type - {0} it not a class.
        /// </summary>
        internal static string C3 {
            get {
                return ResourceManager.GetString("C3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu GoalObjects cannot be a empty collection in time of Goal build.
        /// </summary>
        internal static string C30 {
            get {
                return ResourceManager.GetString("C30", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Precondition 1-arg; There is no {0} param at list. {1}.
        /// </summary>
        internal static string C31 {
            get {
                return ResourceManager.GetString("C31", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Precondition 2-arg; There is no 1st {0} param at list. {1}.
        /// </summary>
        internal static string C32 {
            get {
                return ResourceManager.GetString("C32", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Precondition 2-arg; There is no 2nd {0} param at list. {1}.
        /// </summary>
        internal static string C33 {
            get {
                return ResourceManager.GetString("C33", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu internal error in PreconditionLambdaPDDL constructor: allTypes collection is null.
        /// </summary>
        internal static string C34 {
            get {
                return ResourceManager.GetString("C34", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu internal error in PreconditionLambdaPDDL constructor: allTypes collection is empty.
        /// </summary>
        internal static string C35 {
            get {
                return ResourceManager.GetString("C35", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu internal error in PreconditionLambdaPDDL constructor: paramsIndexesInAction collection is null.
        /// </summary>
        internal static string C36 {
            get {
                return ResourceManager.GetString("C36", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu internal error in PreconditionLambdaPDDL constructor: paramsIndexesInAction collection is empty.
        /// </summary>
        internal static string C37 {
            get {
                return ResourceManager.GetString("C37", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected error in time of Precondition&apos;s function changing: {0}.
        /// </summary>
        internal static string C38 {
            get {
                return ResourceManager.GetString("C38", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You cannot to use object method call to create model of object. Try to write this method ({0}) as new lambda which uses only ValueType member(s) of object..
        /// </summary>
        internal static string C39 {
            get {
                return ResourceManager.GetString("C39", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected error in time of {0} action execution: {1}.
        /// </summary>
        internal static string C4 {
            get {
                return ResourceManager.GetString("C4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There is no {0} parameter inside list..
        /// </summary>
        internal static string C40 {
            get {
                return ResourceManager.GetString("C40", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Its impossible to plan implement agree, cause EventWaitHandle (flon SetExecutionOptions method) is null.
        /// </summary>
        internal static string C41 {
            get {
                return ResourceManager.GetString("C41", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Its impossible to special function agree, cause EventWaitHandle (flon SetExecutionOptions method) is null.
        /// </summary>
        internal static string C42 {
            get {
                return ResourceManager.GetString("C42", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Its impossible to function agree, cause EventWaitHandle (flon SetExecutionOptions method) is null.
        /// </summary>
        internal static string C43 {
            get {
                return ResourceManager.GetString("C43", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There is Index Out Of Range Exception in time of change parameter of action execution lambda.
        /// </summary>
        internal static string C44 {
            get {
                return ResourceManager.GetString("C44", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Among objects of {1} the {2} there is no proper obj. of {0} type..
        /// </summary>
        internal static string C45 {
            get {
                return ResourceManager.GetString("C45", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This domain dont know the {0} class type.
        /// </summary>
        internal static string C5 {
            get {
                return ResourceManager.GetString("C5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected error in time of Action Cost function compilation: {0}.
        /// </summary>
        internal static string C6 {
            get {
                return ResourceManager.GetString("C6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected error in time of Action function compilation: {0}.
        /// </summary>
        internal static string C7 {
            get {
                return ResourceManager.GetString("C7", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected error in time of Action&apos;s cost function compilation: {0}.
        /// </summary>
        internal static string C8 {
            get {
                return ResourceManager.GetString("C8", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed in merge Crisscrosses.
        /// </summary>
        internal static string C9 {
            get {
                return ResourceManager.GetString("C9", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You cannot to create domein without name or with empty name..
        /// </summary>
        internal static string E0 {
            get {
                return ResourceManager.GetString("E0", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Domein with {0} name is already existing..
        /// </summary>
        internal static string E1 {
            get {
                return ResourceManager.GetString("E1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Action name cannot to be empty or undefined..
        /// </summary>
        internal static string E10 {
            get {
                return ResourceManager.GetString("E10", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use only dereferencing of value then: {0}.
        /// </summary>
        internal static string E11 {
            get {
                return ResourceManager.GetString("E11", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use only dereferencing of value then: {0}.
        /// </summary>
        internal static string E12 {
            get {
                return ResourceManager.GetString("E12", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In this version of SharpPDDL its possible to use to 2 params inside Effect function.
        /// </summary>
        internal static string E13 {
            get {
                return ResourceManager.GetString("E13", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Effect name cannot to be empty or undefined..
        /// </summary>
        internal static string E14 {
            get {
                return ResourceManager.GetString("E14", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Effect with {0} name is already existing..
        /// </summary>
        internal static string E15 {
            get {
                return ResourceManager.GetString("E15", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In this version of SharpPDDL its possible to use to 2 params inside action.
        /// </summary>
        internal static string E16 {
            get {
                return ResourceManager.GetString("E16", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Goal obj. cannot be null.
        /// </summary>
        internal static string E17 {
            get {
                return ResourceManager.GetString("E17", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Object used to define goal must be a class. {0} is not a class..
        /// </summary>
        internal static string E18 {
            get {
                return ResourceManager.GetString("E18", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expectations of goal cannot be null value.
        /// </summary>
        internal static string E19 {
            get {
                return ResourceManager.GetString("E19", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You cannot to create action without name or with empty name..
        /// </summary>
        internal static string E2 {
            get {
                return ResourceManager.GetString("E2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expectations of goal cannot be empty collection.
        /// </summary>
        internal static string E20 {
            get {
                return ResourceManager.GetString("E20", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You need use 1 parameter to build goal exception. {0} is wrong.
        /// </summary>
        internal static string E21 {
            get {
                return ResourceManager.GetString("E21", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Member {0} is not a field or property and cannot be use in finding a goal.
        /// </summary>
        internal static string E22 {
            get {
                return ResourceManager.GetString("E22", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You cannot to use object method call to create model of object. Try to write this method ({0})as new lambda which uses only ValueType member(s) of object..
        /// </summary>
        internal static string E23 {
            get {
                return ResourceManager.GetString("E23", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} field have to be: constant / readonly / used as action argument if its not use in param. previesly.
        /// </summary>
        internal static string E24 {
            get {
                return ResourceManager.GetString("E24", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} field variable used in goal checking have to be string or ValueType.
        /// </summary>
        internal static string E25 {
            get {
                return ResourceManager.GetString("E25", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} property variable cannot be changed in time of programm run or have to be used as action argument.
        /// </summary>
        internal static string E26 {
            get {
                return ResourceManager.GetString("E26", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} property variable used in goal checking have to be string or ValueType.
        /// </summary>
        internal static string E27 {
            get {
                return ResourceManager.GetString("E27", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Excetptions inside Goal definition cannot be null.
        /// </summary>
        internal static string E28 {
            get {
                return ResourceManager.GetString("E28", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Excetptions inside Goal definition cannot be empty collection.
        /// </summary>
        internal static string E29 {
            get {
                return ResourceManager.GetString("E29", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Action with {0} name is already existing in {1} domein..
        /// </summary>
        internal static string E3 {
            get {
                return ResourceManager.GetString("E3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu null value cannot be a goal expected abject.
        /// </summary>
        internal static string E30 {
            get {
                return ResourceManager.GetString("E30", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Precondition name cannot to be empty or undefined..
        /// </summary>
        internal static string E31 {
            get {
                return ResourceManager.GetString("E31", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Precondition with {0} name is already existing..
        /// </summary>
        internal static string E32 {
            get {
                return ResourceManager.GetString("E32", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In this version of SharpPDDL its possible to use to 3 params inside Precondition function.
        /// </summary>
        internal static string E33 {
            get {
                return ResourceManager.GetString("E33", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected assiged value to {0}; current value: {1}, expected: {2}. Issue of {3} effect occurred during the execution of {4} action. This variable could be use to check the condition of the next actions..
        /// </summary>
        internal static string E34 {
            get {
                return ResourceManager.GetString("E34", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There is some problem in creating the checker of &quot;{0}&quot; action. .
        /// </summary>
        internal static string E35 {
            get {
                return ResourceManager.GetString("E35", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You cannot to create goal without name or with empty name..
        /// </summary>
        internal static string E4 {
            get {
                return ResourceManager.GetString("E4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu At this version of SharpPDDL you can to find only 1 goal..
        /// </summary>
        internal static string E5 {
            get {
                return ResourceManager.GetString("E5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Its sad. You cannot to use abstract parameter {0}, even if you really want :(.
        /// </summary>
        internal static string E6 {
            get {
                return ResourceManager.GetString("E6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Some parameter of Action Cost is not used in time of action define (precodition or effect).
        /// </summary>
        internal static string E7 {
            get {
                return ResourceManager.GetString("E7", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} is incorrect type to use inside Action Cost function.
        /// </summary>
        internal static string E8 {
            get {
                return ResourceManager.GetString("E8", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There is no possibility of use un-static method like {0} inside of Action Cost funct..
        /// </summary>
        internal static string E9 {
            get {
                return ResourceManager.GetString("E9", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tracing of SharpPDDL lib. is working with &quot;{0}&quot; tracer.
        /// </summary>
        internal static string I0 {
            get {
                return ResourceManager.GetString("I0", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} determined! Total Cost: {1}.
        /// </summary>
        internal static string I1 {
            get {
                return ResourceManager.GetString("I1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In time of &apos;{0}&apos; domain works one add &apos;{1}&apos; - the new effect to it. Algorith will take this new effect on board after external rerun..
        /// </summary>
        internal static string I10 {
            get {
                return ResourceManager.GetString("I10", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In time of &apos;{0}&apos; domain works one add &apos;{1}&apos; - the new execution to it. Algorith will take this new ececution on board after external rerun..
        /// </summary>
        internal static string I11 {
            get {
                return ResourceManager.GetString("I11", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu One changed the action cost in time of domain (which is the owner of it) works. Algorith will take this new action cost on board after external rerun..
        /// </summary>
        internal static string I12 {
            get {
                return ResourceManager.GetString("I12", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Currently, it is not possible to achieve {0} goals. Including it {1} top high priority goals, and {2} high priority goal..
        /// </summary>
        internal static string I13 {
            get {
                return ResourceManager.GetString("I13", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There is no possible to achieve some TOP HIGH priority goal {0}: &apos;{1}&apos;.
        /// </summary>
        internal static string I14 {
            get {
                return ResourceManager.GetString("I14", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There is no possible to achieve some high priority goal {0}: &apos;{1}&apos;.
        /// </summary>
        internal static string I15 {
            get {
                return ResourceManager.GetString("I15", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} is not a class type, so it will be remove from domain objects..
        /// </summary>
        internal static string I2 {
            get {
                return ResourceManager.GetString("I2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New instance of {0} type initialized.
        /// </summary>
        internal static string I3 {
            get {
                return ResourceManager.GetString("I3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu It created a Thumbnail of {0} object from domain obj. with checksum: {1}.
        /// </summary>
        internal static string I4 {
            get {
                return ResourceManager.GetString("I4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Internal reset of Crisscross generator.
        /// </summary>
        internal static string I5 {
            get {
                return ResourceManager.GetString("I5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Checking if all possible state generated.
        /// </summary>
        internal static string I6 {
            get {
                return ResourceManager.GetString("I6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu all possible state probably generated.
        /// </summary>
        internal static string I7 {
            get {
                return ResourceManager.GetString("I7", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected assiged value to {0}; current value: {1}, expected: {2}. Issue of {3} effect occurred during the execution of {4} action..
        /// </summary>
        internal static string I8 {
            get {
                return ResourceManager.GetString("I8", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In time of &apos;{0}&apos; domain works one add &apos;{1}&apos; - the new precondition to it. Algorith will take this new precondition on board after external rerun..
        /// </summary>
        internal static string I9 {
            get {
                return ResourceManager.GetString("I9", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} domain started to create actions&apos; programms.
        /// </summary>
        internal static string Sa0 {
            get {
                return ResourceManager.GetString("Sa0", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Planner of domain started to work.
        /// </summary>
        internal static string Sa1 {
            get {
                return ResourceManager.GetString("Sa1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Begin transcribing the state crisscross.
        /// </summary>
        internal static string Sa10 {
            get {
                return ResourceManager.GetString("Sa10", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start of realization of generated plan.
        /// </summary>
        internal static string Sa2 {
            get {
                return ResourceManager.GetString("Sa2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Begin of {0} action execution, with ID={1}.
        /// </summary>
        internal static string Sa3 {
            get {
                return ResourceManager.GetString("Sa3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start to create Types tree.
        /// </summary>
        internal static string Sa4 {
            get {
                return ResourceManager.GetString("Sa4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Creation of {0} action begin..
        /// </summary>
        internal static string Sa5 {
            get {
                return ResourceManager.GetString("Sa5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Starting of Crisscross Generator..
        /// </summary>
        internal static string Sa6 {
            get {
                return ResourceManager.GetString("Sa6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Begin of new possible states gen., with ID={0}.
        /// </summary>
        internal static string Sa7 {
            get {
                return ResourceManager.GetString("Sa7", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Begin of possible states reducing, with ID={0}.
        /// </summary>
        internal static string Sa8 {
            get {
                return ResourceManager.GetString("Sa8", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Begin goal checking, with ID={0}.
        /// </summary>
        internal static string Sa9 {
            get {
                return ResourceManager.GetString("Sa9", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} domain created actions&apos; programms.
        /// </summary>
        internal static string Sp0 {
            get {
                return ResourceManager.GetString("Sp0", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Abort of plan realization without any action execution. There is DONT_DO_IT mode..
        /// </summary>
        internal static string Sp1 {
            get {
                return ResourceManager.GetString("Sp1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu State crisscross transcribed.
        /// </summary>
        internal static string Sp10 {
            get {
                return ResourceManager.GetString("Sp10", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Current plan fully executed.
        /// </summary>
        internal static string Sp2 {
            get {
                return ResourceManager.GetString("Sp2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Action execution with ID={0} finalized..
        /// </summary>
        internal static string Sp3 {
            get {
                return ResourceManager.GetString("Sp3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Types tree created.
        /// </summary>
        internal static string Sp4 {
            get {
                return ResourceManager.GetString("Sp4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} action created.
        /// </summary>
        internal static string Sp5 {
            get {
                return ResourceManager.GetString("Sp5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Crisscross Generator stoped inside reset function.
        /// </summary>
        internal static string Sp6 {
            get {
                return ResourceManager.GetString("Sp6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stop of new possible states building proces, with ID={0}.
        /// </summary>
        internal static string Sp7 {
            get {
                return ResourceManager.GetString("Sp7", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stop of possible states reducing proces, with ID={0}.
        /// </summary>
        internal static string Sp8 {
            get {
                return ResourceManager.GetString("Sp8", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stop of goal checking proces, with ID={0}.
        /// </summary>
        internal static string Sp9 {
            get {
                return ResourceManager.GetString("Sp9", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0}: .
        /// </summary>
        internal static string Txt1 {
            get {
                return ResourceManager.GetString("Txt1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Action cost: {0}.
        /// </summary>
        internal static string Txt2 {
            get {
                return ResourceManager.GetString("Txt2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu External cancellation token at {0} domain.
        /// </summary>
        internal static string V0 {
            get {
                return ResourceManager.GetString("V0", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} domein started to find solution..
        /// </summary>
        internal static string V1 {
            get {
                return ResourceManager.GetString("V1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} the goal was removed from goals to realize list..
        /// </summary>
        internal static string V10 {
            get {
                return ResourceManager.GetString("V10", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Object of {0}-type was removed from {1} domain..
        /// </summary>
        internal static string V11 {
            get {
                return ResourceManager.GetString("V11", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Object of {0}-type was added to {1} domain..
        /// </summary>
        internal static string V12 {
            get {
                return ResourceManager.GetString("V12", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plan accepted..
        /// </summary>
        internal static string V2 {
            get {
                return ResourceManager.GetString("V2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Waiting for plan acceptation..
        /// </summary>
        internal static string V3 {
            get {
                return ResourceManager.GetString("V3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There is NO agree to plan realization / cancellation of implementor working.
        /// </summary>
        internal static string V4 {
            get {
                return ResourceManager.GetString("V4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Waiting for special action {0} acceptation..
        /// </summary>
        internal static string V5 {
            get {
                return ResourceManager.GetString("V5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Waiting for action {0} acceptation..
        /// </summary>
        internal static string V6 {
            get {
                return ResourceManager.GetString("V6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There is NO agree to {0} action realization / cancellation of implementor working.
        /// </summary>
        internal static string V7 {
            get {
                return ResourceManager.GetString("V7", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There is agree to {0} action realization.
        /// </summary>
        internal static string V8 {
            get {
                return ResourceManager.GetString("V8", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You added action sententia with reference to object, but without params. Try to use: AddPartOfActionSententia({0});.
        /// </summary>
        internal static string V9 {
            get {
                return ResourceManager.GetString("V9", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You asked to accept some executions, but you didnt give the lib. any WaitHandle to do it..
        /// </summary>
        internal static string W0 {
            get {
                return ResourceManager.GetString("W0", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected value change. Its impossible to realize {0} action, cause {1} precondition is unfulfilled..
        /// </summary>
        internal static string W1 {
            get {
                return ResourceManager.GetString("W1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You asked to accept some executions, but you didnt give the lib. any Event to inform you about waiting on it..
        /// </summary>
        internal static string W10 {
            get {
                return ResourceManager.GetString("W10", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You forgot to define of acceptation of action realize param. It will ask of everything..
        /// </summary>
        internal static string W11 {
            get {
                return ResourceManager.GetString("W11", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected assiged value to {0}; current value: {1}, expected: {2}. Issue of {3} effect occurred during the execution of {4} action. This variable could be use to figure another value of effect..
        /// </summary>
        internal static string W12 {
            get {
                return ResourceManager.GetString("W12", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected assiged value to {0}; current value: {1}, expected: {2}. Issue of {3} effect occurred during the execution of {4} action. This variable could be use to aproximate a cost of action..
        /// </summary>
        internal static string W13 {
            get {
                return ResourceManager.GetString("W13", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You added {0}-th action sententia, with action text &quot;{1}&quot;. Didn&apos;t you forget about params?.
        /// </summary>
        internal static string W14 {
            get {
                return ResourceManager.GetString("W14", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Goal: {0} is added to finding the solution of it. You cannot to change it now. New part will be ignored..
        /// </summary>
        internal static string W15 {
            get {
                return ResourceManager.GetString("W15", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expectations for {1}-type object inside {0} the goal was defined previously. Redefinition / add new ones is ignored..
        /// </summary>
        internal static string W16 {
            get {
                return ResourceManager.GetString("W16", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu One of actions have no declared execution. SharpPDDL is trying realize plan without this action.
        /// </summary>
        internal static string W2 {
            get {
                return ResourceManager.GetString("W2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Added part of action sententia is empty..
        /// </summary>
        internal static string W3 {
            get {
                return ResourceManager.GetString("W3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lack of parameters inside {0} action. It will not be use..
        /// </summary>
        internal static string W4 {
            get {
                return ResourceManager.GetString("W4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There is no executions of {0} action..
        /// </summary>
        internal static string W5 {
            get {
                return ResourceManager.GetString("W5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Action name cannot to start with &apos;{0}&apos;. New action name is {1}.
        /// </summary>
        internal static string W6 {
            get {
                return ResourceManager.GetString("W6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There is no {0} key inside {1} action sententia..
        /// </summary>
        internal static string W7 {
            get {
                return ResourceManager.GetString("W7", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There is {0} key inside {1} action sententia, but is less param to this.
        /// </summary>
        internal static string W8 {
            get {
                return ResourceManager.GetString("W8", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Precondition funct is without parameter. Its constant result of that..
        /// </summary>
        internal static string W9 {
            get {
                return ResourceManager.GetString("W9", resourceCulture);
            }
        }
    }
}
