//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpPDDL.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesOfVisualization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesOfVisualization() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpPDDL.Properties.ResourcesOfVisualization", typeof(ResourcesOfVisualization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} (Case Use Diagram){1}.
        /// </summary>
        internal static string ActFileName {
            get {
                return ResourceManager.GetString("ActFileName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu LeftToRight.
        /// </summary>
        internal static string ActGraphDirection {
            get {
                return ResourceManager.GetString("ActGraphDirection", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sugiyama.
        /// </summary>
        internal static string ActGraphLayout {
            get {
                return ResourceManager.GetString("ActGraphLayout", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Case Use Diagram.
        /// </summary>
        internal static string ActGraphTitle {
            get {
                return ResourceManager.GetString("ActGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu «include».
        /// </summary>
        internal static string ActIncludeLabelKey {
            get {
                return ResourceManager.GetString("ActIncludeLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ♦ .
        /// </summary>
        internal static string ActPrecBullet {
            get {
                return ResourceManager.GetString("ActPrecBullet", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu «realization».
        /// </summary>
        internal static string ActRealizeLabelKey {
            get {
                return ResourceManager.GetString("ActRealizeLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Actions List:.
        /// </summary>
        internal static string CriActListHead {
            get {
                return ResourceManager.GetString("CriActListHead", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0}: {1}.
        /// </summary>
        internal static string CriActListRecord {
            get {
                return ResourceManager.GetString("CriActListRecord", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Action Name.
        /// </summary>
        internal static string CriActNaLabelKey {
            get {
                return ResourceManager.GetString("CriActNaLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Action Sententia.
        /// </summary>
        internal static string CriActSenLabelKey {
            get {
                return ResourceManager.GetString("CriActSenLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Action Cost.
        /// </summary>
        internal static string CriCostLabelKey {
            get {
                return ResourceManager.GetString("CriCostLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cumulative Cost.
        /// </summary>
        internal static string CriCumCostLabelKey {
            get {
                return ResourceManager.GetString("CriCumCostLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} (State Diagram){1}.
        /// </summary>
        internal static string CriFileName {
            get {
                return ResourceManager.GetString("CriFileName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu LeftToRight.
        /// </summary>
        internal static string CriGraphDirection {
            get {
                return ResourceManager.GetString("CriGraphDirection", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ForceDirected.
        /// </summary>
        internal static string CriGraphLayout {
            get {
                return ResourceManager.GetString("CriGraphLayout", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu States of {0} domain.
        /// </summary>
        internal static string CriGraphTitle {
            get {
                return ResourceManager.GetString("CriGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is in realize.
        /// </summary>
        internal static string CriInRealizeLabelKey {
            get {
                return ResourceManager.GetString("CriInRealizeLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0}  🔘.
        /// </summary>
        internal static string CriStateFinish {
            get {
                return ResourceManager.GetString("CriStateFinish", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ⚫  {0}.
        /// </summary>
        internal static string CriStateStart {
            get {
                return ResourceManager.GetString("CriStateStart", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} (Class Diagram){1}.
        /// </summary>
        internal static string TypFileName {
            get {
                return ResourceManager.GetString("TypFileName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu BottomToTop.
        /// </summary>
        internal static string TypGraphDirection {
            get {
                return ResourceManager.GetString("TypGraphDirection", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sugiyama.
        /// </summary>
        internal static string TypGraphLayout {
            get {
                return ResourceManager.GetString("TypGraphLayout", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Types&apos; graph.
        /// </summary>
        internal static string TypGraphTitle {
            get {
                return ResourceManager.GetString("TypGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pointer ℗.
        /// </summary>
        internal static string TypPointer {
            get {
                return ResourceManager.GetString("TypPointer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Used as cost funct. input.
        /// </summary>
        internal static string TypVCostInLabelKey {
            get {
                return ResourceManager.GetString("TypVCostInLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Used as effect input.
        /// </summary>
        internal static string TypVEffInLabelKey {
            get {
                return ResourceManager.GetString("TypVEffInLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Used as effect output.
        /// </summary>
        internal static string TypVEffOutLabelKey {
            get {
                return ResourceManager.GetString("TypVEffOutLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Internal number.
        /// </summary>
        internal static string TypVNr {
            get {
                return ResourceManager.GetString("TypVNr", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Used as precondition input.
        /// </summary>
        internal static string TypVPreInLabelKey {
            get {
                return ResourceManager.GetString("TypVPreInLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Type.
        /// </summary>
        internal static string TypVTypeLabelKey {
            get {
                return ResourceManager.GetString("TypVTypeLabelKey", resourceCulture);
            }
        }
    }
}
